### ISSUE TITLE
403 forbidden on /usr/share/nginx/html when rebuilding

### ISSUE THREAD

**Issue by msansoni** [koddr/example-static-website-docker-nginx-certbot#1]
Thanks for this example! Awesome effort, ssl certification on docker has always casued me so many headaches.

One question, when I stop the containers, and even remove the images, when I re-make the deployment  `make deploy-prod`, I recieve a 403 nginx error, with the /usr/share/nginx/html access being forbidden. I wonder if this is due to the way the volumes are exposed across the containers, and if there is a way these can be presented without forbidding entry post standing the containers down.

**Comment by koddr** [comment]
Hmm.. interesting. It's happen only if you stopped containers for the first time?

**Comment by msansoni** [comment]
When I deploy on the droplet for the first time, all works well. If I stop the containers, remove them and images, pull a code change and then stand up the prod again, a 403 error is returned, this happens on every restart. Rebuilding the droplet fixes this.
Do you think there's a way nginx could be presented the files from a container rather than the host?

**Comment by koddr** [comment]
> Do you think there's a way nginx could be presented the files from a container rather than the host?

Maybe, yes. But I can't reproduce this on my local or DO droplet :(

**Comment by msansoni** [comment]
It's very likely I'm doing something silly then! :) Out of interest, what commands are you using to stop the containers, [pull new frontend code], and restart?
Thanks for your help!

**Comment by msansoni** [comment]
I increased the logging verbosity of nginx:
`2020/04/02 19:21:15 [error] 8#8: *24 directory index of "/usr/share/nginx/html/" is forbidden`

I'm standing down the containers pretty aggressively:
```shell
docker stop $(docker ps -q)
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
docker system prune
```
I've attempted only standing down the `docker-compose.prod.yml`. However struggled to isolate container and volumes.

**Comment by koddr** [comment]
@msansoni I use `make deploy-prod` (from [Makefile](https://github.com/koddr/example-static-website-docker-nginx-certbot/blob/master/Makefile)). But I'm on macOS, don't know, how it works on Windows 🤷

**Comment by msansoni** [comment]
Hey @koddr.

In the end I made a stand-down directive in the makefile, before pulling the new code, which meant I could automate deployment from a push to the repo. Don't know if you're interested but might make a nice final step in your tutorial for full CD.

```make
stand-down:
	@docker-compose \
				-f docker-compose.yml \
				-f docker-compose.prod.yml \
			       down -v
```

Which enables this to be used in a Github action.
```yaml
steps:
      - name: Build and deploy prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: |
              make stand-down
              git pull
              make deploy-prod
```
